name: Install Terraform

on:
  push:
    branches:
      - main
jobs:
  install-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.4 # Specify the version of Terraform you want to use
